version: '3'
services:
  workstation:
    image: hossein20s/docker-workstation:unity3D
    container_name: workstation
#     command: tail -f /dev/null
    privileged: true
    ports:
      - 4321:4000
    environment:
      DISPLAY: $DISPLAY # for mac DISPLAY=docker.for.mac.host.internal:0 # --before running docker-compose and after running xhost +
      USER: developer
      PASSWORD: developer
    cap_add:
      - SYS_PTRACE
    volumes:
      - ${HOME}:/opt/host
      - /dev/shm:/dev/shm
      # - ${HOME}/docker-workstation/developer:/home/developer # uncomment to persists user home
