apiVersion: v1
kind: Pod
metadata:
  name: notebook
spec:
  containers:
  - name: notebook
    image: hossein20s/jpython-notebook-pod
    ports:
    - containerPort: 8888
    resources:
      limits:
        cpu: "1.5"
      requests:
        cpu: "500m"
