apiVersion: v1
kind: Pod
metadata:
  name: notebook
spec:
  containers:
  - name: note3
    image: hossein20s/docker-workstation:notebook-ml
    ports:
    - containerPort: 8888
    resources:
      limits:
        cpu: "1.5"
      requests:
        cpu: "500m"
