kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifacts
spec:
  storageClassName: "aws-efs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
---
kind: List
apiVersion: v1
items:
  - kind: Service
    apiVersion: v1
    metadata:
      name: notebook-service
    spec:
      selector:
        app: notebook # This must match the app label applied in the Deployment created below
      ports:
        - port: 8888
          targetPort: 8888
#       type: LoadBalancer
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: notebook-deployment
    spec:
      replicas: 1
#      selector:
#        matchLabels:
#          app: notebook
      template:
        metadata:
          labels:
            app: notebook
        spec:
          containers:
          - name: notebook
            image: hossein20s/docker-workstation:notebook-ml
            ports:
            - containerPort: 8888
            resources:
              limits:
                cpu: "500m"
                memory: 2000Mi
              requests:
                cpu: "100m"
                memory: 256Mi
            volumeMounts:
              - mountPath: /opt/artifacts
                name: artifacts-volume
          volumes:
            - name: artifacts-volume
              persistentVolumeClaim:
                claimName: artifacts
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      annotations:
        kubernetes.io/ingress.class: internal
      name: notebook-ingress
    spec:
      tls:
      - hosts:
        - $INGRESS_HOST
        secretName: tls-secret
      rules:
      - host: $INGRESS_HOST
        http:
          paths:
          - path: /notebook
            backend:
              serviceName: notebook-service
              servicePort: 8888
