version: '3'
services:
  workstation:
    image: hossein20s/docker-workstation:mobile
    container_name: workstation
#     command: tail -f /dev/null
    privileged: true
    # network_mode: "host"
    ports:
      - 4000:4000
      - 5000:5000
    environment:
      DISPLAY: # : $DISPLAY # for mac DISPLAY=docker.for.mac.host.internal:0 # --before running docker-compose and after running xhost +
      XAUTHORITY: /tmp/.docker.xauth
      USER: developer
      PASSWORD: developer
    cap_add:
      - SYS_PTRACE
    volumes:
      - ~:/opt/host
      - /dev/shm:/dev/shm
      # - ${HOME}/docker-workstation/Ubuntu-20.4/nomachine/etc/server.cfg:/usr/NX/etc/server.cfg
      - developer:/home/developer # uncomment to persists user home
      # the following is for X11 DISPLAY from http://wiki.ros.org/docker/Tutorials/GUI
      # you need to : touch /tmp/.docker.xauth
      # xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f /tmp/.docker.xauth nmerge -
      # - /tmp/.X11-unix:/tmp/.X11-unix
      # - /tmp/.docker.xauth:/tmp/.docker.xauthx
      - dev:/opt/dev
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
volumes:
  dev:
    external: true
  developer:
    external: true
