name: ag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - ansible
  - alembic
  - pip
  - pip:
##    # works for regular pip packages
    - APScheduler==3.6.0
    - attrs==18.2.0
    - boto3==1.9.62
    - celery==4.2.1
    - ciso8601==2.1.3
    - click==7.0
    - croniter==0.3.30
    - deprecation==2.1.0
    - freezegun==0.3.11
    - geopy==1.11.0
    - python2-secrets==1.0.5
    - deepmerge==0.1.0
#    - dask==2.17.2
    - deprecation==2.1.0
    - django-bootstrap3==9.0.0
    - django-celery-beat==1.4.0
    - django-crispy-forms==1.6.0
    - django-extensions==1.9.8
    - django-filter==1.1.0
    - django-mysql==2.2.0
    - django-tables2==1.16.0
    - Django==1.11.26
    - djangorestframework-jwt==1.11.0
    - djangorestframework==3.4.0
    - dogpile.cache==0.6.2
    - emails==0.5.13
#    - future==0.16.0
    - gunicorn==19.1.1
    - happybase==1.1.0
    - hiredis==0.2.0
    - influxdb==5.2.0
    - ipdb==0.10.1
    - ipython==4.2.0
    - Jinja2==2.8
    - kafka-python==1.4.2
    - kombu==4.5.0
    - matplotlib==1.5.3
    - mock==1.3.0
#    - mysqlclient==1.3.9
    - networkx==1.11
    - newrelic==4.14.0.115
    - nose-exclude==0.4.1
    - nose==1.3.7
    - numpy==1.16.3
    - objgraph==3.1.0
    - packaging==20.1
    - pandas==0.24.1
    - path.py==7.7.1
    - patsy==0.4.1
    - pika==0.9.8
    - pvlib==0.5.0
    - py4j==0.10.8.1
    - Pyomo==5.2
    - pytz==2017.2
    - PyUtilib==5.8.0
#    - PyYAML==4.2b4
    - redis==2.10.6
    - requests==2.21.0
    - rest-framework-auth0==0.4.5
    - scikit-learn==0.17.1
    - scipy==0.19.1
    - scp==0.10.2
    - sendgrid==1.2.3
    - shortuuid==0.5.0
    - simplejson==3.5.3
    - six==1.12.0
#    - SQLAlchemy-Utc==0.9.0
#    - SQLAlchemy-Utils==0.31.4
#    - SQLAlchemy==1.3.3
    - statsmodels==0.8.0
    - unittest-xml-reporting==2.5.1
#    - urllib3==1.25.9
#    - wheel==0.24.0
#    - whitenoise==3.2
