name: ag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.8
  - ansible
#  - alembic
#  - APScheduler=3.6.0
#  - attrs=18.2.0
#  - boto3=1.9.62
#  - celery=4.2.1
#  - ciso8601=2.1.3
#  - click=7.0
#  - croniter=0.3.30
#  - deprecation=2.1.0
#  - freezegun=0.3.11
#  - geopy=1.11.0
#  - happybase=1.1.0
#  - hiredis=0.2.0
#  - ipdb=0.10.1
##  - ipython=4.2.0
##  - Jinja2=2.8
##  - kombu=4.5.0
##  - matplotlib=1.5.3
#  - mock=1.3.0
#  - networkx=1.11
#  - newrelic=4.14.0.115
#  - nose=1.3.7
##  - numpy=1.16.3
#  - packaging=20.1
#  - patsy=0.4.1
#  - py4j=0.10.8.1
#  - Pyomo=5.2
##  - python2-secrets=1.0.5
##  - pytz
##  - pytz=2017.2
##  - PyUtilib=5.8.0
##  - scikit-learn=0.17.1
##  - scipy=0.19.1
#  - scp=0.10.2
#  - shortuuid=0.5.0
#  - six=1.12.0
#  - six>=1.7
#  - statsmodels=0.8.0
##  - pip
##  - pip:
##    # works for regular pip packages
##    - docx
##    - gooey
##    - gunicorn==19.1.1
##    - wheel==0.24.0
##    - sendgrid==1.2.3
##    - sqlalchemy-utc==0.9.0
##    - dogpile.cache==0.6.2
##    - kafka-python==1.4.2
##    - django-mysql
##    - objgraph==3.1.0
##    - deepmerge==0.1.0
##    - mysqlclient==1.3.9
##     - whitenoise==3.2
##    - unittest-xml-reporting==2.5.1
##    - django[version=='1.11.26.*,1.11.3.*']
##    - django-celery-beat==1.4.0
##    - pvlib==0.5.0
##    - redis==2.10.6
##    - simplejson==3.5.3
##    - emails==0.5.13
##    - pika==0.9.8
##    - sqlalchemy-utils==0.31.4
##    - django-crispy-forms==1.6.0
##    - pyyaml[version=='3.10.*,4.2b4.*']
##    - path.py==7.7.1
##    - django-tables2==1.16.0
##    - rest-framework-auth0==0.4.5
##    - nose-exclude==0.4.1
##    - influxdb==5.2.0
